package byx.service.tx;

/**
 * Taxonomia FECHADA de erros de transação. O wire usa só o nome do enum; mensagens de exceção, detalhes do nó e dados da transação nunca viajam.
 * Qualquer falha não prevista vira {@link #INTERNAL}.
 */
public enum TxError {
    TX_DISABLED, UNAUTHORIZED, MFA_REQUIRED, ELEVATION_REQUIRED, BAD_REQUEST,
    INVALID_ADDRESS, INVALID_AMOUNT, INVALID_FEE_MODE, MEMO_TOO_LARGE,
    SIMULATION_FAILED, GAS_ESTIMATE_INVALID, MAX_GAS_EXCEEDED, MAX_FEE_EXCEEDED, ACCOUNT_INVALID,
    QUOTE_EXPIRED, QUOTE_NOT_FOUND, QUOTE_MISMATCH, CHAIN_CHANGED, STALE_SEQUENCE,
    SIGNER_UNAVAILABLE, SIGNING_FAILED, BROADCAST_FAILED, UNKNOWN_OUTCOME,
    INSUFFICIENT_FUNDS, FEE_TOO_LOW, OUT_OF_GAS, TOO_MANY_OPERATIONS, INTERNAL
}
