package panel.security;

public enum AuditEvent {
    INITIAL_ADMIN_CREATED, LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT,
    ADMIN_ACCESS_TRUSTED_IPV6, ADMIN_ACCESS_DENIED, ADMIN_2FA_STARTED, ADMIN_2FA_SUCCESS, ADMIN_2FA_FAILED, ADMIN_SESSION_EXPIRED,
    USER_CREATED, USER_DISABLED, USER_ENABLED, ROLE_CHANGED, PASSWORD_CHANGED, PASSWORD_RESET
}
