package panel.security;

public enum AuditEvent {
    INITIAL_ADMIN_CREATED, LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT,
    EMAIL_OTP_SENT, EMAIL_OTP_VERIFIED, EMAIL_OTP_FAILED,
    SMS_VERIFY_SENT, SMS_VERIFY_APPROVED, SMS_VERIFY_FAILED,
    TRUSTED_DEVICE_CREATED, TRUSTED_DEVICE_USED, TRUSTED_DEVICE_REVOKED, TRUSTED_DEVICE_EXPIRED,
    ADMIN_ACCESS_2FA, ADMIN_ACCESS_TRUSTED_DEVICE, CONTACT_CHANGED, ADMIN_ACCESS_DENIED, ADMIN_2FA_STARTED, ADMIN_2FA_SUCCESS, ADMIN_2FA_FAILED, ADMIN_SESSION_EXPIRED,
    USER_CREATED, USER_DISABLED, USER_ENABLED, ROLE_CHANGED, PASSWORD_CHANGED, PASSWORD_RESET
}
