package panel.ui;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.VBox;
import panel.app.AppContext;
import panel.model.FeatureInfo;
import panel.model.Snapshot;
import panel.util.Fmt;

public class FeaturesView extends PageView {
    public FeaturesView(AppContext ctx) {
        super(ctx);
    }

    @Override
    protected void build(Snapshot s, VBox page) {
        page.getChildren().add(Ui.pageHeader("Features", "Causal microstructure features generated by the backend (no computation in the panel)"));
        page.getChildren().add(Ui.card("Feature set",
                Ui.kvNode("Status", Ui.stateBadge(s.featureState)),
                Ui.kv("Sessions complete", Fmt.ratio(s.featureDone, s.labelsTotalSessions())),
                Ui.kv("Schema", s.featureSchema), Ui.kv("Rows", Fmt.num(s.anchorCount)),
                Ui.kv("Coverage / missing values", "N/A — not exposed by the backend yet")));
        Map<String, List<FeatureInfo>> byCat = new LinkedHashMap<>();
        s.features.forEach(f -> byCat.computeIfAbsent(f.category(), k -> new java.util.ArrayList<>()).add(f));
        byCat.forEach((cat, list) -> {
            GridPane g = new GridPane();
            g.setHgap(18);
            g.setVgap(8);
            for (int ci = 0; ci < 8; ci++) {
                javafx.scene.layout.ColumnConstraints cc = new javafx.scene.layout.ColumnConstraints();
                if (ci == 2 || ci == 3) {
                    cc.setHgrow(javafx.scene.layout.Priority.ALWAYS);
                    cc.setMinWidth(120);
                } else {
                    cc.setMinWidth(javafx.scene.layout.Region.USE_PREF_SIZE);
                }
                g.getColumnConstraints().add(cc);
            }
            String[] head = {"Feature", "Status", "Schema", "Columns", "Coverage", "Missing", "Last generated", "Hash"};
            for (int i = 0; i < head.length; i++) {
                g.add(Ui.label(head[i], "muted"), i, 0);
            }
            int r = 1;
            for (FeatureInfo f : list) {
                g.add(Ui.label(f.name(), "kv-value"), 0, r);
                g.add(Ui.stateBadge(f.state()), 1, r);
                javafx.scene.control.Label schema = Ui.label(Fmt.text(f.schema()), "mono");
                schema.setWrapText(true);
                g.add(schema, 2, r);
                javafx.scene.control.Label cols = Ui.label(f.columns().isEmpty() ? Fmt.NA : String.join(", ", f.columns()), "mono");
                cols.setWrapText(true);
                cols.setMaxWidth(Double.MAX_VALUE);
                g.add(cols, 3, r);
                g.add(Ui.label(Fmt.NA, "muted"), 4, r);
                g.add(Ui.label(Fmt.NA, "muted"), 5, r);
                g.add(Ui.label(f.lastGenerated() == null ? Fmt.NA : Fmt.dateTime(java.time.Instant.parse(f.lastGenerated())), "muted"), 6, r);
                g.add(Ui.label(Fmt.shortHash(f.hash()), "mono"), 7, r++);
            }
            page.getChildren().add(Ui.card(cat, g));
        });
    }
}
