package byx.service.chain;

/** Razões FECHADAS de falha/estado do conector da chain pública. Nunca texto vindo do nó. */
public enum ChainReason {
    NONE, NOT_CONFIGURED,
    UNREACHABLE, TIMEOUT, HTTP_STATUS, REDIRECT_REFUSED, RESPONSE_TOO_LARGE,
    JSON_INVALID, SCHEMA_INVALID, MISSING_FIELD, TYPE_MISMATCH, VALUE_OUT_OF_RANGE,
    NETWORK_MISMATCH, DENOM_MISMATCH, HEIGHT_REGRESSION, BLOCK_TIME_IN_FUTURE, NODE_STALE, CATCHING_UP
}
