package panel;

import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import javafx.scene.*;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import org.junit.jupiter.api.*;
import panel.design.*;
import panel.i18n.*;
import panel.motion.*;
import panel.model.TraderSnapshot.Candle;
import panel.shell.avatar.*;

/** Native runtime contracts; synthetic UI fixtures contain no network or wallet authority. */
class PackageC2ThemeTest {
    @AfterEach void reset() throws Exception { FxSupport.fx(() -> { ByxTheme.resetSession(); Strings.resetSession(); }); }
    @Test void startupWithoutPreferenceUsesDark() throws Exception { FxSupport.fx(() -> { ByxTheme.resetSession(); assertEquals(ThemeMode.DARK,ByxTheme.mode()); }); }
    @Test void lightInitializationResolvesExactApprovedTokens() throws Exception { FxSupport.fx(() -> { ByxTheme.select(ThemeMode.LIGHT);assertEquals(Color.web("#1C2639"),ByxTheme.color(ThemeToken.TEXT_PRIMARY)); }); }
    @Test void all115TokensExistInBothPalettes() { assertEquals(115,ThemeToken.values().length);for(var mode:List.of(ThemeMode.DARK,ThemeMode.LIGHT)) {assertEquals(115,ThemePalette.of(mode).size());for(var token:ThemeToken.values())assertNotNull(ThemePalette.of(mode).color(token),token.key);} }
    @Test void themeResourcesArePresentAndMissingResourceCannotSilentlyLoad() { assertEquals(ByxTheme.STYLESHEETS.size(),ByxTheme.urls().size());for(String path:ByxTheme.STYLESHEETS)assertNotNull(ByxTheme.class.getResource(path));assertThrows(IllegalStateException.class,()->ByxTheme.stylesheetUrl("/panel/v2/missing-c2.css")); }
    @Test void systemIsExplicitlyUnsupportedWithoutChangingCurrentMode() throws Exception { FxSupport.fx(() -> {assertFalse(ByxTheme.systemSupported());assertThrows(IllegalArgumentException.class,()->ByxTheme.select(ThemeMode.SYSTEM));assertEquals(ThemeMode.DARK,ByxTheme.mode());}); }
    @Test void updatesRequireFxThread() { assertThrows(IllegalStateException.class,()->ByxTheme.select(ThemeMode.LIGHT)); }
    @Test void switchingKeepsInputsSelectionScrollAndNodeIdentity() throws Exception { FxSupport.fx(() -> {TextField input=new TextField("ETHUSDT draft 1.234567");input.selectRange(2,7);ScrollPane scroll=new ScrollPane(new VBox(input));scroll.setVvalue(.4);VBox root=new VBox(scroll);Scene scene=new Scene(root,1100,700);ByxTheme.apply(scene);ByxTheme.select(ThemeMode.LIGHT);assertSame(root,scene.getRoot());assertEquals("ETHUSDT draft 1.234567",input.getText());assertEquals(2,input.getSelection().getStart());assertEquals(7,input.getSelection().getEnd());assertEquals(.4,scroll.getVvalue());}); }
    @Test void switchingPreservesRealSceneFocus() throws Exception { FxSupport.fx(() -> {TextField field=new TextField("draft");Scene scene=new Scene(new VBox(field),400,200);ByxTheme.apply(scene);Stage stage=new Stage();stage.setScene(scene);stage.show();field.requestFocus();Node focus=scene.getFocusOwner();assertSame(field,focus);ByxTheme.select(ThemeMode.LIGHT);assertSame(focus,scene.getFocusOwner());stage.close();}); }
    @Test void dialogsRemainOpenWithTheSameActionAndContent() throws Exception { FxSupport.fx(() -> {MotionService motion=new MotionService();motion.preference.set(MotionPreference.OFF);ByxOverlayHost host=new ByxOverlayHost(new VBox(),motion);Scene scene=new Scene(host,1100,700);ByxTheme.apply(scene);int[] calls={0};var handle=host.confirm("Settings","Review draft","Confirm",false,()->calls[0]++);List<Node> nodes=new ArrayList<>(host.getChildren());ByxTheme.select(ThemeMode.LIGHT);assertEquals(1,host.openDialogs());assertEquals(nodes,host.getChildren());assertEquals(0,calls[0]);handle.close();host.dispose();}); }
    @Test void openMenuContentIsNotRecreated() throws Exception { FxSupport.fx(() -> {ContextMenu menu=new ContextMenu(new MenuItem("ETHUSDT"));Button anchor=new Button("Menu");Scene scene=new Scene(new VBox(anchor),400,200);ByxTheme.apply(scene);Stage stage=new Stage();stage.setScene(scene);stage.show();menu.show(anchor,javafx.geometry.Side.BOTTOM,0,0);MenuItem item=menu.getItems().getFirst();ByxTheme.select(ThemeMode.LIGHT);assertTrue(menu.isShowing());assertSame(item,menu.getItems().getFirst());assertTrue(menu.getScene().getRoot().getPseudoClassStates().contains(javafx.css.PseudoClass.getPseudoClass("byx-theme-light")));menu.hide();stage.close();}); }
    @Test void pendingOperationAndPresentationSurviveSwitch() throws Exception { FxSupport.fx(() -> {long[] now={0};OperationRegistry registry=new OperationRegistry(()->now[0],MascotTokens.shared());var token=registry.begin("synthetic pending");now[0]=400;var state=registry.presentation();ByxTheme.select(ThemeMode.LIGHT);assertEquals(1,registry.pending());assertEquals(state,registry.presentation());registry.end(token,true,null);assertEquals(0,registry.pending());}); }
    @Test void localeAndThemeAreIndependent() throws Exception { FxSupport.fx(() -> {Strings.use(Strings.Lang.PT_BR);ByxTheme.select(ThemeMode.LIGHT);assertEquals(Strings.Lang.PT_BR,Strings.language());Strings.use(Strings.Lang.EN);assertEquals(ThemeMode.LIGHT,ByxTheme.mode());}); }
    @Test void serverAuthorizationRemainsDeniedInBothThemes() throws Exception { FxSupport.fx(() -> {for(var mode:List.of(ThemeMode.DARK,ThemeMode.LIGHT)){ByxTheme.select(mode);assertThrows(panel.security.AccessDeniedException.class,()->panel.security.ServerAuthorization.require(panel.security.ServerOperation.SETTINGS_PREFERENCES_PERSIST));}}); }
    @Test void appearanceHasNoPersistenceAndResetsBySession() throws Exception { FxSupport.fx(() -> {ByxTheme.select(ThemeMode.LIGHT);ByxTheme.resetSession();assertEquals(ThemeMode.DARK,ByxTheme.mode());}); }
    @Test void cachedDetachedRootReceivesCurrentThemeAfterNavigation() throws Exception { FxSupport.fx(() -> {VBox cached=new VBox(new Label("ETHUSDT"));ByxTheme.apply(cached);Scene scene=new Scene(new VBox());ByxTheme.apply(scene);ByxTheme.select(ThemeMode.LIGHT);scene.setRoot(cached);assertTrue(cached.getPseudoClassStates().contains(javafx.css.PseudoClass.getPseudoClass("byx-theme-light")));}); }
    @Test void detachedPaintObserverDoesNotDuplicateOrReactUntilReattached() throws Exception { FxSupport.fx(() -> {VBox node=new VBox();int[] paints={0};ByxTheme.observe(node,()->paints[0]++);Scene scene=new Scene(node);ByxTheme.apply(scene);ByxTheme.select(ThemeMode.LIGHT);int before=paints[0];scene.setRoot(new VBox());ByxTheme.select(ThemeMode.DARK);assertEquals(before,paints[0]);scene.setRoot(node);assertEquals(before+1,paints[0]);ByxTheme.select(ThemeMode.LIGHT);assertEquals(before+2,paints[0]);}); }
    @Test void canvasRepaintsWithoutChangingCandleDataOrGeometry() throws Exception { FxSupport.fx(() -> {List<Candle> data=List.of(new Candle(100,105,98,103,1),new Candle(103,104,97,99,2));var chart=new panel.ui.trader.CandleChart(data);StackPane root=new StackPane(chart);Scene scene=new Scene(root,640,340);ByxTheme.apply(scene);root.applyCss();root.layout();var dark=scene.snapshot(null);ByxTheme.select(ThemeMode.LIGHT);root.applyCss();root.layout();var light=scene.snapshot(null);assertEquals(dark.getWidth(),light.getWidth());assertNotEquals(dark.getPixelReader().getArgb(570,100),light.getPixelReader().getArgb(570,100));assertEquals(new Candle(100,105,98,103,1),data.getFirst());}); }
    @Test void marketSemanticsAndFinancialValuesAreInvariant() {for(var mode:List.of(ThemeMode.DARK,ThemeMode.LIGHT)){Color up=ThemePalette.of(mode).color(ThemeToken.CHART_CANDLE_UP),down=ThemePalette.of(mode).color(ThemeToken.CHART_CANDLE_DOWN);assertTrue(up.getGreen()>up.getRed());assertTrue(down.getRed()>down.getGreen());}var value=new java.math.BigDecimal("2480.840001");assertEquals("2480.840001",value.toPlainString());}
    @Test void mascotBodyAndEyesAreInvariant() {for(var token:List.of(ThemeToken.AVATAR_BODY,ThemeToken.AVATAR_EYES))assertEquals(ThemePalette.of(ThemeMode.DARK).color(token),ThemePalette.of(ThemeMode.LIGHT).color(token));}
    @Test void allMotionModesAndMascotPoseStayUnchangedAtSwitch() throws Exception { FxSupport.fx(() -> {for(var mode:AvatarMotion.Mode.values()){AvatarMotion engine=new AvatarMotion(MascotTokens.shared());engine.setMode(mode);engine.setPointer(.5,.6);var pose=engine.tick(100,OperationRegistry.Presentation.LOADING);ByxTheme.select(ThemeMode.LIGHT);assertSame(pose,engine.pose());ByxTheme.select(ThemeMode.DARK);assertSame(pose,engine.pose());}}); }
    @Test void nativeAppearanceChoiceRemainsEditableAndLocalized() throws Exception { FxSupport.fx(() -> {ThemeSelector selector=new ThemeSelector();Scene scene=new Scene(new VBox(selector));ByxTheme.apply(scene);RadioButton light=(RadioButton)selector.lookup("#appearance-light"),system=(RadioButton)selector.lookup("#appearance-system");assertFalse(light.isDisabled());assertTrue(system.isDisabled());light.fire();assertEquals(ThemeMode.LIGHT,ByxTheme.mode());Strings.use(Strings.Lang.PT_BR);assertEquals("Claro",light.getText());}); }
    @Test void switchingHasNoBackendOrFilesystemDependencies() throws Exception {String source=java.nio.file.Files.readString(java.nio.file.Path.of("src/main/java/panel/design/ByxTheme.java"));for(String prohibited:List.of("HttpClient","savePrefs","ProcessBuilder","Files.write","Runtime.getRuntime","ServerAuthorization","sessions."))assertFalse(source.contains(prohibited),prohibited);}
    @Test void legacyBoundaryReceivesLightTokensWithoutLeakingIntoShell() throws Exception { FxSupport.fx(() -> {Label label=new Label("Legacy");var legacy=new panel.shell.LegacyHost(label);VBox root=new VBox(legacy);Scene scene=new Scene(root);ByxTheme.apply(scene);ByxTheme.select(ThemeMode.LIGHT);root.applyCss();assertEquals(ThemePalette.of(ThemeMode.LIGHT).color(ThemeToken.TEXT_PRIMARY),label.getTextFill());}); }
    @Test void chartPointerAndTechnicalOhlcTooltipSurvivePaletteChange() throws Exception { FxSupport.fx(() -> {
        var data=List.of(new Candle(100.1234,105.5,98.01,103.2222,1));var chart=new panel.ui.trader.CandleChart(data);var root=new StackPane(chart);var scene=new Scene(root,640,340);ByxTheme.apply(scene);root.applyCss();root.layout();
        chart.getOnMouseMoved().handle(new javafx.scene.input.MouseEvent(javafx.scene.input.MouseEvent.MOUSE_MOVED,200,120,200,120,javafx.scene.input.MouseButton.NONE,0,false,false,false,false,false,false,false,false,false,false,null));
        try {var pointer=chart.getClass().getDeclaredField("pointerX");pointer.setAccessible(true);var tooltip=chart.getClass().getDeclaredField("candleTooltip");tooltip.setAccessible(true);String before=((Tooltip)tooltip.get(chart)).getText();ByxTheme.select(ThemeMode.LIGHT);root.applyCss();root.layout();assertEquals(200,pointer.getDouble(chart));assertEquals(before,((Tooltip)tooltip.get(chart)).getText());assertTrue(before.contains("100.1234"));Strings.use(Strings.Lang.PT_BR);assertTrue(((Tooltip)tooltip.get(chart)).getText().contains("100,1234"));assertEquals(new Candle(100.1234,105.5,98.01,103.2222,1),data.getFirst());}catch(ReflectiveOperationException e){throw new RuntimeException(e);}
    }); }
    @Test void flatCandleRendersFiniteNativePixelsInBothThemes() throws Exception { FxSupport.fx(() -> {
        var chart=new panel.ui.trader.CandleChart(List.of(new Candle(100,100,100,100,1)));var root=new StackPane(chart);var scene=new Scene(root,640,340);ByxTheme.apply(scene);
        for(var theme:List.of(ThemeMode.DARK,ThemeMode.LIGHT)){ByxTheme.select(theme);root.applyCss();root.layout();var image=scene.snapshot(null);assertEquals(640,image.getWidth());assertNotEquals(image.getPixelReader().getArgb(280,170),image.getPixelReader().getArgb(285,175));}
    }); }

}
